version: '3.3'
services:
  node-red:
    ports:
      - '1880:8080'
    image: 'nodered/node-red:latest-12-minimal'
    volumes:
      - './:/data'
    user: root:root
    working_dir: /data
    entrypoint:
    - sh
    - -c
    - "npm install && npm start --cache /data/.npm"
