version: '3.3'
services:
  node-red:
    environment:
      - FLOWS=flows.json
    ports:
      - '8080:8080'
    image: 'nodered/node-red:latest-minimal'
    volumes:
      - './:/data'
    user: root:root
